language: php

sudo: false

matrix:
  include:
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*

cache:
  directories:
    - ~/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - if [ ! -z ${SYMFONY_VERSION+x} ]; then composer require --no-update "symfony/config:${SYMFONY_VERSION}"; fi
  - composer install --prefer-dist

script: vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com
