language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.* PHPUNIT_VERSION=^5.7
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: hhvm

cache:
  directories:
    - ~/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - if [ ! -z ${SYMFONY_VERSION+x} ]; then composer require --no-update "symfony/config:${SYMFONY_VERSION}"; fi
  - if [ ! -z ${PHPUNIT_VERSION+x} ]; then composer require --no-update "phpunit/phpunit:${PHPUNIT_VERSION}"; fi
  - composer update --prefer-dist

notifications:
  email: matthiasnoback@gmail.com
